
import type { Artist, Category } from '@/lib/types';

export const artistsData: Artist[] = [
    {
        id: '1',
        name: "Café",
        instagramTag: "@ocabadasfoto",
        category: "Audiovisual",
        subCategories: ["Photography", "Videomaker", "Video Editing"],
        description: "MULTITALENTO",
        imageUrl: "https://i.ibb.co/Tnm0WjW/IMG-9533.jpg",
        instagramLink: "@ocabadasfoto",
        portfolioLink: "(Link)",
    },
    {
        id: '2',
        name: "Thiago Nômade",
        instagramTag: "@artnomadebr",
        category: "Artesanato",
        subCategories: ["Couro", "Miçangas", "Colares", "Desenho"],
        description: "Desenhista, joalheiro, artes em couro, artista plástico e tatuador",
        imageUrl: "https://i.ibb.co/fJGcp9B/IMG-9534.jpg",
        instagramLink: "@artnomadebr",
        portfolioLink: "(Link)",
    },
    {
        id: '3',
        name: "Igor & Flor",
        instagramTag: "@igoreflor",
        category: "Música",
        subCategories: ["Música ao vivo", "Casamentos", "Festas", "MPB"],
        description: "MPB, música latina, surf, trips e arte!",
        imageUrl: "https://i.ibb.co/kVYgZRW7/IMG-9536.jpg",
        instagramLink: "@igoreflor",
        youtubeLink: "(Link)",
    },
    {
        id: '4',
        name: "Thiberio Leite",
        instagramTag: "@thiberloopmusic",
        category: "Música",
        subCategories: ["DJ", "Eletrônica", "House"],
        description: "DJ residente no Sombra e Agua, Pipa Beach Club e 420 Beach Bar",
        imageUrl: "https://i.ibb.co/1GwgvBLs/IMG-9537.jpg",
        instagramLink: "@thiberloopmusic",
        youtubeLink: "(Link)",
    },
    {
        id: '5',
        name: "Agustin Diaz",
        instagramTag: "@djagus.diaz",
        category: "Música",
        subCategories: ["DJ", "Funk", "Reggeaton"],
        description: "DJ residente no Dudo Bar",
        imageUrl: "https://i.ibb.co/4ZWmHf6G/IMG-9538.jpg",
        instagramLink: "@djagus.diaz",
        youtubeLink: "(Link)",
    },
    {
        id: '6',
        name: "Day Música",
        instagramTag: "@daymusica",
        category: "Música",
        subCategories: ["Música ao vivo", "Internacional", "MPB", "Festas"],
        description: "Musicista, dupla com percucionista Gabriel Ceballos",
        imageUrl: "https://i.ibb.co/6ccvyPT8/IMG-9539.jpg",
        instagramLink: "@daymusica",
        youtubeLink: "(Link)",
    },
    {
        id: '7',
        name: "Gabriel Ceballos",
        instagramTag: "@ranagramx",
        category: "Música",
        subCategories: ["Música ao vivo", "Percussão", "Bateria"],
        description: "Percucionista, dupla com Day Música",
        imageUrl: "https://i.ibb.co/Fkrp9rZR/IMG-9551.jpg",
        instagramLink: "@ranagramx",
        youtubeLink: "(Link)",
    },
    {
        id: '8',
        name: "Th97",
        instagramTag: "@th97art",
        category: "Artes Visuais",
        subCategories: ["Muralista", "Street Art"],
        description: "Muralista Street Art em movimento",
        imageUrl: "https://i.ibb.co/RqB6Zxv/IMG-9540.jpg",
        instagramLink: "@th97art",
        portfolioLink: "(Link)",
    },
    {
        id: '9',
        name: "Ras Barack",
        instagramTag: "@rasbarack",
        category: "Música",
        subCategories: ["DJ", "Reggae", "Composição"],
        description: "Cantor, Compositor e DJ. Discotecagem Baile",
        imageUrl: "https://i.ibb.co/WN3jDwvv/IMG-9541.jpg",
        instagramLink: "@rasbarack",
        youtubeLink: "(Link)",
    },
    {
        id: '10',
        name: "Trio Caju",
        instagramTag: "@triocajumpb",
        category: "Música",
        subCategories: ["Música ao vivo", "Banda", "MPB"],
        description: "Irmandade musical de resgate e valorização da Música Popular Brasileira",
        imageUrl: "https://i.ibb.co/nNsVZdkV/IMG-9542.jpg",
        instagramLink: "@triocajumpb",
        youtubeLink: "(Link)",
    },
    {
        id: '11',
        name: "DJubi Roots",
        instagramTag: "@djubi_roots",
        category: "Música",
        subCategories: ["DJ", "Reggae"],
        description: "DJ, Personal Trainer, Pesquisador Musical, Produtor e Amante de Reggae music",
        imageUrl: "https://i.ibb.co/8gq41W95/IMG-9543.jpg",
        instagramLink: "@djubi_roots",
        youtubeLink: "(Link)",
    },
    {
        id: '12',
        name: "Andressa \"Multiplica\"",
        instagramTag: "@and.multiplica",
        category: "Artesanato",
        subCategories: ["Miçanga", "Colares", "Pulseiras", "Brincos"],
        description: "Artesanato direto de Pipa",
        imageUrl: "https://i.ibb.co/hJ99WKzW/IMG-9544.jpg",
        instagramLink: "@and.multiplica",
        portfolioLink: "(Link)",
    },
    {
        id: '13',
        name: "Larissa Pereira",
        instagramTag: "@llarissapereiraa_",
        category: "Música",
        subCategories: ["DJ"],
        description: "DJ da Fonte",
        imageUrl: "https://i.ibb.co/hRRRXG2Z/IMG-9545.jpg",
        instagramLink: "@llarissapereiraa_",
        youtubeLink: "(Link)",
    },
    {
        id: '14',
        name: "ROOTS",
        instagramTag: "@roots.originalstyle",
        category: "Roupas",
        subCategories: ["Moda de Praia", "Roupas", "Reggae"],
        description: "Roupas com atitude. Sinta a vibe, vista a essência",
        imageUrl: "https://i.ibb.co/N2QPF2Lz/IMG-9546.jpg",
        instagramLink: "@roots.originalstyle",
        portfolioLink: "(Link)",
    },
    {
        id: '15',
        name: "Igor Barros",
        instagramTag: "@inkbarros",
        category: "Tatuagem",
        subCategories: ["Fine Line", "Realismo", "OldSchool"],
        description: "Tatuador residente no Ateliê de Tattoo na Mata Atlântica",
        imageUrl: "https://i.ibb.co/84BZRG0n/IMG-9547.jpg",
        instagramLink: "@inkbarros",
        portfolioLink: "(Link)",
    },
    {
        id: '16',
        name: "Xerderson Nascimento",
        instagramTag: "@xerdeson",
        category: "Artes Visuais",
        subCategories: ["Muralista", "Pintor"],
        description: "Em cada maré, encontro a força e a sabedoria de Iemanjá",
        imageUrl: "https://i.ibb.co/C5LhnQcw/IMG-9549.jpg",
        instagramLink: "@xerdeson",
        portfolioLink: "(Link)",
    },
    {
        id: '17',
        name: "Gabriel Castello",
        instagramTag: "@gabochan",
        category: "Música",
        subCategories: ["Música ao vivo", "Teclado", "Aulas"],
        description: "Pianista, professor, membro do Tropical Vibes Band",
        imageUrl: "https://i.ibb.co/DgKhPK0p/IMG-9578.jpg",
        instagramLink: "@gabochan",
        youtubeLink: "(Link)",
    },
    {
        id: '18',
        name: "Klebson Ferraz",
        instagramTag: "@klebsonferraz",
        category: "Audiovisual",
        subCategories: ["Fotografia", "Videomaking", "Marketing", "Autor"],
        description: "Videomaker, fotógrafo, autor, faço som, vendo com tráfico",
        imageUrl: "https://i.ibb.co/prrqyh4T/IMG-9562.jpg",
        instagramLink: "@klebsonferraz",
        portfolioLink: "(Link)",
    },
    {
        id: '19',
        name: "Luiz Lima",
        instagramTag: "@luizlimarn",
        category: "Música",
        subCategories: ["Música ao vivo", "MPB", "Pop", "Festas"],
        description: "Música ao vivo que transforma sua noite, Voz e Violão",
        imageUrl: "https://i.ibb.co/1Y8g35dt/IMG-9563.jpg",
        instagramLink: "@luizlimarn",
        youtubeLink: "(Link)",
    },
    {
        id: '20',
        name: "Ymani Ralyson",
        instagramTag: "@ymani.art",
        category: "Performance",
        subCategories: ["Pirofagia", "Atuação", "Coreografía", "Balé"],
        description: "Faço arte com o corpo, com o fogo e com a alma",
        imageUrl: "https://i.ibb.co/Q7nym387/IMG-9564.jpg",
        instagramLink: "@ymani.art",
        portfolioLink: "(Link)",
    },
    {
        id: '21',
        name: "DJ Solfol",
        instagramTag: "@solfol___",
        category: "Música",
        subCategories: ["DJ", "House"],
        description: "DJ residente do Makai Club. Piercing",
        imageUrl: "https://i.ibb.co/1YcZvf3P/IMG-9565.jpg",
        instagramLink: "@solfol___",
        youtubeLink: "(Link)",
    },
    {
        id: '22',
        name: "Tefi Sommer",
        instagramTag: "@tefisommer",
        category: "Música",
        subCategories: ["Música ao vivo", "Composição", "Internacional"],
        description: "Transformando a rua em palco, com o sonho de lotar um estádio",
        imageUrl: "https://i.ibb.co/rG5mp4kM/IMG-9566.jpg",
        instagramLink: "@tefisommer",
        youtubeLink: "(Link)",
    },
    {
        id: '23',
        name: "Naná Rodrigues",
        instagramTag: "@nanarodriguesx",
        category: "Gastronomia",
        subCategories: ["Chef", "Consultoria", "Saudável"],
        description: "Personal Chef & Consultora Gastronômica",
        imageUrl: "https://i.ibb.co/cX34fqV1/IMG-9567.jpg",
        instagramLink: "@nanarodriguesx",
        portfolioLink: "(Link)",
    },
    {
        id: '24',
        name: "Anismario dos Santos",
        instagramTag: "@anismariosantanadossantos",
        category: "Artesanato",
        subCategories: ["Pulseiras", "Ferro", "Jóias"],
        description: "Artesão e Músico",
        imageUrl: "https://i.ibb.co/j9DpnWjh/IMG-9568.jpg",
        instagramLink: "@anismariosantanadossantos",
        portfolioLink: "(Link)",
    },
    {
        id: '25',
        name: "Barraca do Berón",
        instagramTag: "@spa.cejungle",
        category: "Espaços",
        subCategories: ["DJ", "Eletrônica"],
        description: "Música eletrônica na praia até o sol nascer",
        imageUrl: "https://i.ibb.co/sdHHZt6f/IMG-9569.jpg",
        instagramLink: "@spa.cejungle",
        portfolioLink: "(Link)",
    },
    {
        id: '26',
        name: "Martin Salutto",
        instagramTag: "@martinsalutto",
        category: "Música",
        subCategories: ["Música ao vivo", "Internacional"],
        description: "Membro do grupo Rua do Sol trio",
        imageUrl: "https://i.ibb.co/bjwbT9w4/IMG-9571.jpg",
        instagramLink: "@martinsalutto",
        youtubeLink: "(Link)",
    },
    {
        id: '27',
        name: "Beco Beija Flor",
        instagramTag: "@becobeijaflor",
        category: "Espaços",
        subCategories: ["Pintura", "Decoração", "Mural"],
        description: "Galeria de arte gratuita em Pipa",
        imageUrl: "https://i.ibb.co/FvJkw4g/IMG-9572.jpg",
        instagramLink: "@becobeijaflor",
        portfolioLink: "(Link)",
    },
    {
        id: '28',
        name: "Marcos Andrade",
        instagramTag: "@marcaochefnoronha",
        category: "Gastronomia",
        subCategories: ["Chef", "Frutos do Mar"],
        description: "Chefe do Sofi Bistrô",
        imageUrl: "https://i.ibb.co/8LncFkSN/IMG-9574.jpg",
        instagramLink: "@marcaochefnoronha",
        portfolioLink: "(Link)",
    },
    {
        id: '29',
        name: "Barbara Potiguara",
        instagramTag: "@indiabarbara",
        category: "Gastronomia",
        subCategories: ["Chef", "Vegano", "Saudável"],
        description: "Arte, Cultura e Culinária Nativa",
        imageUrl: "https://i.ibb.co/hx6M86cs/IMG-9575.jpg",
        instagramLink: "@indiabarbara",
        portfolioLink: "(Link)",
    },
    {
        id: '30',
        name: "Abanole",
        instagramTag: "@aba_nole",
        category: "Performance",
        subCategories: ["Pirofagia", "Figurinista", "Dança"],
        description: "Multi artista, ator, performer, pernas de pau",
        imageUrl: "https://i.ibb.co/7JxggtjW/IMG-9577.jpg",
        instagramLink: "@aba_nole",
        portfolioLink: "(Link)",
    },
    {
        id: '31',
        name: "Boteco do Pirata",
        instagramTag: "@botecodopirata",
        category: "Espaços",
        subCategories: ["Pintura", "Leitura", "Roupas"],
        description: "Feira de livros, roupas, arte e música ao vivo",
        imageUrl: "https://i.ibb.co/DgPHcqSJ/IMG-9580.jpg",
        instagramLink: "@botecodopirata",
        portfolioLink: "(Link)",
    }
];

export const categories: Category[] = ["Artes Visuais", "Artesanato", "Audiovisual", "Espaços", "Gastronomia", "Música", "Performance", "Roupas", "Tatuagem"];

    

    

    

    